server:
  port: 10011 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: user-service # 用户服务
          uri:
            lb://user-service
          predicates:
            - Path=/user/**,/auth/**
        - id: image-service # 图片服务
          uri:
            lb://image-service
          predicates:
            - Path=/image/**
        - id: audit-service # 审核服务
          uri:
            lb://audit-service
          predicates:
            - Path=/audit/**
        - id: video-info-service # 视频信息服务
          uri:
            lb://video-info-service
          predicates:
            - Path=/video/info/**
        - id: video-upload-service # 视频上传服务
          uri:
            lb://video-upload-service
          predicates:
            - Path=/video/upload/**
        - id: video-play-service # 视频播放服务
          uri:
            lb://video-play-service
          predicates:
            - Path=/video/play/**
        - id: video-processing-service # 视频转码/信息服务
          uri:
            lb://video-processing-service
          predicates:
            - Path=/video/processing/**
        - id: analytics-service # 统计分析服务
          uri:
            lb://analytics-service
          predicates:
            - Path=/analytics/**
        - id: feed-service # 推荐服务
          uri:
            lb://feed-service
          predicates:
            - Path=/feed/**
        - id: like-favorite-service # 视频点赞/收藏服务
          uri:
            lb://like-favorite-service
          predicates:
            - Path=/like/**,/favorite/**
        - id: comment-service # 评论服务
          uri:
            lb://comment-service
          predicates:
            - Path=/comment/**
        - id: social-service # 社交关系服务
          uri:
            lb://social-service
          predicates:
            - Path=/social/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
