server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: user-service # 用户服务
          uri:
            lb://user-service
          predicates:
            - Path=/user/**
        - id: image-service # 图片服务
          uri:
            lb://image-service
          predicates:
            - Path=/image/**
        - id: audit-service # 审核服务
          uri:
            lb://audit-service
          predicates:
            - Path=/audit/**
        - id: video-upload-service # 视频上传服务
          uri:
            lb://video-upload-service
          predicates:
            - Path=/video/upload/**
        - id: video-play-service # 视频播放服务
          uri:
            lb://video-play-service
          predicates:
            - Path=/video/play/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
