spring:
  application:
    name: video-processing-service  # 应用名
  config:
    import: nacos:common-config
  cloud:
    nacos:
      config:
        file-extension: yaml
server:
  port: 30304 # 端口号





